[phases.setup]
nixPkgs = ['python39', 'gcc', 'pkg-config', 'mysql', 'bash']

[phases.install]
cmds = ['python3.9 -m pip install --upgrade pip', 'python3.9 -m pip install -r requirements.txt']

[phases.build]
cmds = ['python3.9 -c "print(\"✅ Build completed\")"']

[start]
cmd = 'bash start.sh'
